name: Trigger auto deployment for nodejsapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/nodejsapp-AutoDeployTrigger-392d49df-4dcf-40f2-bb9f-8a043af209af.yml'

  # Allow manual trigger 
  workflow_dispatch:      
jobs:
  CI:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.IMAGE }}
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        id: build
        env:
          IMAGE: app:NodeJSAppExample-${{ env.GITHUB_RUN_ID }}
          ENDPOINT: ${{ secrets.ACR_ENDPOINT }}
        run: | 
          docker build -t $ENDPOINT/$IMAGE .
          docker push $ENDPOINT/$IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        imageToDeploy: ${{ secrets.ACR_ENDPOINT }}/${{needs.CI.outputs.endpoint.image}}
        containerAppName: njsapp